CREATE TABLE `CAR COMPANY` (
	`PK_A`	VARCHAR(50)	NOT NULL,
	`COMPANY_NAME`	VARCHAR(50)	NULL,
	`CAR_NAME`	VARCHAR(50)	NULL,
	`CAR_YEAR`	VARCHAR(50)	NULL
);

CREATE TABLE `OPTION` (
	`PK_B`	VARCHAR(50)	NOT NULL,
	`OPTION`	VARCHAR(50)	NULL
);

CREATE TABLE `OPTION_INFO` (
	`PK_C`	VARCHAR(255)	NOT NULL,
	`PK_A`	VARCHAR(255)	NOT NULL,
	`PK_B`	VARCHAR(255)	NOT NULL
);

ALTER TABLE `CAR COMPANY` ADD CONSTRAINT `PK_CAR COMPANY` PRIMARY KEY (
	`PK_A`
);

ALTER TABLE `OPTION` ADD CONSTRAINT `PK_OPTION` PRIMARY KEY (
	`PK_B`
);

ALTER TABLE `OPTION_INFO` ADD CONSTRAINT `PK_OPTION_INFO` PRIMARY KEY (
	`PK_C`,
	`PK_A`,
	`PK_B`
);

ALTER TABLE `OPTION_INFO` ADD CONSTRAINT `FK_CAR COMPANY_TO_OPTION_INFO_1` FOREIGN KEY (
	`PK_A`
)
REFERENCES `CAR COMPANY` (
	`PK_A`
);

ALTER TABLE `OPTION_INFO` ADD CONSTRAINT `FK_OPTION_TO_OPTION_INFO_1` FOREIGN KEY (
	`PK_B`
)
REFERENCES `OPTION` (
	`PK_B`
);

