INSERT INTO `NOTICE_CONTENTS` (PK_A, CONTENTS, WRITER)
VALUES ('A001', '서비스 점검 안내', '관리자');
INSERT INTO `NOTICE_CONTENTS` (PK_A, CONTENTS, WRITER)
VALUES ('A002', '이벤트 안내', '마케팅팀');
INSERT INTO `NOTICE_CONTENTS` (PK_A, CONTENTS, WRITER)
VALUES ('A003', '새로운 기능 추가 안내', '관리자');
INSERT INTO `NOTICE_CONTENTS` (PK_A, CONTENTS, WRITER)
VALUES ('A004', '결제 시스템 업그레이드 안내', '운영팀');
INSERT INTO `NOTICE_CONTENTS` (PK_A, CONTENTS, WRITER)
VALUES ('A005', '서비스 이용약관 변경 안내', '운영팀');

INSERT INTO `NOTICE_VISITOR` (PK_B, FK_A, VISITOR)
VALUES ('B_01','A001','홍길동');
INSERT INTO `NOTICE_VISITOR` (PK_B, FK_A, VISITOR)
VALUES ('B_06','A001','김영희');
INSERT INTO `NOTICE_VISITOR` (PK_B, FK_A, VISITOR)
VALUES ('B_02','A002','백지영');
INSERT INTO `NOTICE_VISITOR` (PK_B, FK_A, VISITOR)
VALUES ('B_07','A002','최민호');
INSERT INTO `NOTICE_VISITOR` (PK_B, FK_A, VISITOR)
VALUES ('B_08','A002','송지현');
INSERT INTO `NOTICE_VISITOR` (PK_B, FK_A, VISITOR)
VALUES ('B_03','A003','장성우');
INSERT INTO `NOTICE_VISITOR` (PK_B, FK_A, VISITOR)
VALUES ('B_04','A004','백지영');
INSERT INTO `NOTICE_VISITOR` (PK_B, FK_A, VISITOR)
VALUES ('B_09','A004','최민호');
INSERT INTO `NOTICE_VISITOR` (PK_B, FK_A, VISITOR)
VALUES ('B_10','A004','임현서');
INSERT INTO `NOTICE_VISITOR` (PK_B, FK_A, VISITOR)
VALUES ('B_05','A005','강수민');
INSERT INTO `NOTICE_VISITOR` (PK_B, FK_A, VISITOR)
VALUES ('B_11','A005','백지영');
INSERT INTO `NOTICE_VISITOR` (PK_B, FK_A, VISITOR)
VALUES ('B_12','A005','박정희');
